// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKx5N3wYg1WeNeOgseqpa8VhZEO6QXWpY',
    appId: '1:916860410731:web:525485d26c896e7f3b8a2e',
    messagingSenderId: '916860410731',
    projectId: 'petmealai',
    authDomain: 'petmealai.firebaseapp.com',
    storageBucket: 'petmealai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMR5rgUerAvTg3YKE1n7XQ48_Q32_-C0',
    appId: '1:916860410731:android:029ddbc2e3f6844d3b8a2e',
    messagingSenderId: '916860410731',
    projectId: 'petmealai',
    storageBucket: 'petmealai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3bPLP7MbtKjRuN5Wo_SKcENpjX0YuaLE',
    appId: '1:916860410731:ios:9e3c1728ba2cd0b33b8a2e',
    messagingSenderId: '916860410731',
    projectId: 'petmealai',
    storageBucket: 'petmealai.firebasestorage.app',
    androidClientId: '916860410731-ttbgbob7a893cm0dgagh6ffi2bmduoei.apps.googleusercontent.com',
    iosClientId: '916860410731-72o5ak1bdaq1arslf4vjm3pgc2ldj9fa.apps.googleusercontent.com',
    iosBundleId: 'com.mealplanner.foodofdogs.petmeal.calDogsAi',
  );

}